name: fredriksen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15983
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#010101'
    - '#9e9e9e'
    - '#6f6f6f'
    - '#353535'
  brandStrength: 0.5
  lightness: 0.6978947774041444
  saturation: 0.43264251737855375
  rhythmicContrast: 0.7402176281902939
purpose: []
